<a href="https://colab.research.google.com/github/evanstrait/DAFT_1022/blob/main/Module_1/Lab_24_Numpy/Lab_24_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [ ]:
import numpy as np

#### 2. Print your NumPy version.

In [ ]:
print(np.__version__)

1.21.6


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [ ]:
a = np.random.randint(0, 100, size=(30, 10, 2))
a

array([[[ 8, 53],
        [17, 69],
        [73, 35],
        [82,  1],
        [95, 76],
        [80, 91],
        [78, 54],
        [ 3, 69],
        [13,  3],
        [ 9, 34]],

       [[83, 10],
        [97, 72],
        [89, 17],
        [52, 42],
        [87, 97],
        [99, 88],
        [ 2,  0],
        [67, 58],
        [17, 46],
        [68, 97]],

       [[96, 19],
        [ 8, 98],
        [84, 80],
        [28, 71],
        [ 1, 83],
        [34, 21],
        [34, 56],
        [ 4, 67],
        [18, 47],
        [ 1, 45]],

       [[18, 36],
        [74, 97],
        [98, 74],
        [38, 72],
        [44, 82],
        [42, 25],
        [73, 37],
        [89, 48],
        [35,  6],
        [88, 60]],

       [[46, 88],
        [89, 31],
        [54,  4],
        [34, 79],
        [32, 90],
        [29, 25],
        [47, 65],
        [ 0, 24],
        [32, 83],
        [99, 84]],

       [[38, 94],
        [78, 21],
        [70, 74],
        [93, 84],
        [16, 41],


In [ ]:
a = np.random.random((2,3,5))
a

array([[[0.2047125 , 0.70057063, 0.4383161 , 0.23968729, 0.77735451],
        [0.69594071, 0.34993801, 0.54283286, 0.76602819, 0.32146841],
        [0.12630958, 0.64686627, 0.26902696, 0.62085578, 0.38882065]],

       [[0.25736836, 0.12776343, 0.88467585, 0.29177428, 0.87111674],
        [0.26855656, 0.13596461, 0.74796036, 0.76913368, 0.59722095],
        [0.92600308, 0.95705134, 0.17365072, 0.06811664, 0.25065037]]])

In [ ]:
a = np.random.sample((2, 3, 5))
a

array([[[0.60773982, 0.15454453, 0.7286028 , 0.4382703 , 0.57226058],
        [0.74526347, 0.71310251, 0.89617673, 0.8456983 , 0.65007401],
        [0.0024545 , 0.76118549, 0.35503609, 0.92606635, 0.06236549]],

       [[0.51433019, 0.61905392, 0.7547112 , 0.34159115, 0.56817892],
        [0.11320736, 0.04420043, 0.47660279, 0.00383606, 0.24512767],
        [0.4061511 , 0.53902413, 0.88223225, 0.6232404 , 0.95817012]]])

#### 4. Print *a*.


In [ ]:
 a

array([[[0.2047125 , 0.70057063, 0.4383161 , 0.23968729, 0.77735451],
        [0.69594071, 0.34993801, 0.54283286, 0.76602819, 0.32146841],
        [0.12630958, 0.64686627, 0.26902696, 0.62085578, 0.38882065]],

       [[0.25736836, 0.12776343, 0.88467585, 0.29177428, 0.87111674],
        [0.26855656, 0.13596461, 0.74796036, 0.76913368, 0.59722095],
        [0.92600308, 0.95705134, 0.17365072, 0.06811664, 0.25065037]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [ ]:
b=np.ones((5,2,3))

#### 6. Print *b*.


In [ ]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [ ]:
# your code here
if a.size == b.size:
    print("They have the same size!")
else:
    print("They do not.")


They have the same size!


#### 8. Are you able to add *a* and *b*? Why or why not?


In [ ]:
print("No we are not able to add because even tho they have the same size they have different shapes.")
#c=a+b


No we are not able to add because even tho they have the same size they have different shapes.


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [ ]:
# your code here
c = np.transpose(b, axes=(1, 2, 0))
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [ ]:
# your code/answer here
d = a + c
d.shape

(2, 3, 5)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [ ]:
print(a[0])
print(d[0])

[[0.2047125  0.70057063 0.4383161  0.23968729 0.77735451]
 [0.69594071 0.34993801 0.54283286 0.76602819 0.32146841]
 [0.12630958 0.64686627 0.26902696 0.62085578 0.38882065]]
[[1.2047125  1.70057063 1.4383161  1.23968729 1.77735451]
 [1.69594071 1.34993801 1.54283286 1.76602819 1.32146841]
 [1.12630958 1.64686627 1.26902696 1.62085578 1.38882065]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [ ]:
e = a * c
print(e)

[[[0.2047125  0.70057063 0.4383161  0.23968729 0.77735451]
  [0.69594071 0.34993801 0.54283286 0.76602819 0.32146841]
  [0.12630958 0.64686627 0.26902696 0.62085578 0.38882065]]

 [[0.25736836 0.12776343 0.88467585 0.29177428 0.87111674]
  [0.26855656 0.13596461 0.74796036 0.76913368 0.59722095]
  [0.92600308 0.95705134 0.17365072 0.06811664 0.25065037]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
if np.array_equal(e, a):
    print("Yes they're the same!")

Yes they're the same!


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [ ]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(d_max)
print(d_min)
print(d_mean)

1.9570513363792281
1.068116637997068
1.4805245133720362


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [ ]:
# your code here
f = np.empty([2, 3, 5])
f

array([[[0.2047125 , 0.70057063, 0.4383161 , 0.23968729, 0.77735451],
        [0.69594071, 0.34993801, 0.54283286, 0.76602819, 0.32146841],
        [0.12630958, 0.64686627, 0.26902696, 0.62085578, 0.38882065]],

       [[0.25736836, 0.12776343, 0.88467585, 0.29177428, 0.87111674],
        [0.26855656, 0.13596461, 0.74796036, 0.76913368, 0.59722095],
        [0.92600308, 0.95705134, 0.17365072, 0.06811664, 0.25065037]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [ ]:
f = []
for x in np.nditer(d):
    if d_min < x < d_mean:
        f += [25]
    if d_mean < x < d_max:
        f += [75]
    if x == d_mean:
        f += [50]
    if x == d_min:
        f += [0]
    if x == d_max:
        f += [100]
    
        
f = np.reshape(f, d.shape) 
print(f)

[[[ 25  75  25  25  75]
  [ 75  25  75  75  25]
  [ 25  75  25  75  25]]

 [[ 25  25  75  25  75]
  [ 25  25  75  75  75]
  [ 75 100  25   0  25]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here
print(d)
print(f)

[[[1.60773982 1.15454453 1.7286028  1.4382703  1.57226058]
  [1.74526347 1.71310251 1.89617673 1.8456983  1.65007401]
  [1.0024545  1.76118549 1.35503609 1.92606635 1.06236549]]

 [[1.51433019 1.61905392 1.7547112  1.34159115 1.56817892]
  [1.11320736 1.04420043 1.47660279 1.00383606 1.24512767]
  [1.4061511  1.53902413 1.88223225 1.6232404  1.95817012]]]
[[[ 75  25  75  25  75]
  [ 75  75  75  75  75]
  [  0  75  25  75  25]]

 [[ 25  75  75  25  75]
  [ 25  25  25  25  25]
  [ 25  75  75  75 100]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
j = []
for x in np.nditer(d):
    if d_min < x < d_mean:
        j += ['B']
    if d_mean < x < d_max:
        j += ['D']
    if x == d_mean:
        j += ['C']
    if x == d_min:
        j += ['A']
    if x == d_max:
        j += ['E']
    
j = np.reshape(j, d.shape) 
print(j)


[[['D' 'B' 'D' 'B' 'D']
  ['D' 'D' 'D' 'D' 'D']
  ['A' 'D' 'B' 'D' 'B']]

 [['B' 'D' 'D' 'B' 'D']
  ['B' 'B' 'B' 'B' 'B']
  ['B' 'D' 'D' 'D' 'E']]]
